; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25547.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Joseph\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
